version: '3'
services:

  shadowsocksr:
  #   image: burndown/ssr:v1
     build: .
     ports:
      - "80:58388"
     environment:
      - METHOD=aes-256-cfb
      - PASSWORD=TfYyW72A
      - PROTOCOL=auth_aes128_md5
      - OBFS=tls1.2_ticket_auth_compatible
      - OBFS_PARAM=github.com
     restart: always
