shadowsocks:
  image: burndown/ss:v1
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=Killgfw!
  restart: always

shadowsocksr:
   image: burndown/ssr:v1
   ports:
    - "80:58388"
   environment:
    - METHOD=aes-256-cfb
    - PASSWORD=Killgfw!
    - PROTOCOL=auth_aes128_md5
    - OBFS=tls1.2_ticket_auth_compatible
    - OBFS_PARAM=www.icpppy.com
   restart: always
