shadowsocks:
  image: burndown/ss:v1
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=Killgfw!
  restart: always

shadowsocksr:
   image: burndown/ssr:v1
   ports:
    - "80:58388"
   restart: always
